from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.patches import Circle, ConnectionPatch, Rectangle

from common import detector_readout, intensity_from_components


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare Lumerical detector-plane fields against Python reference outputs."
    )
    parser.add_argument(
        "--case",
        required=True,
        help="Path to case_data.npz generated by prepare_case.py.",
    )
    parser.add_argument(
        "--monitor",
        required=True,
        help="Path to lumerical_monitor_output.npz generated by run_fdtd_b.py or an equivalent export.",
    )
    parser.add_argument(
        "--save-json",
        default="",
        help="Optional JSON output path for comparison metrics.",
    )
    parser.add_argument(
        "--save-png",
        default="",
        help="Optional PNG output path for visualization figure.",
    )
    return parser.parse_args()


def _load_monitor_field(monitor_npz: np.lib.npyio.NpzFile, key: str):
    if key not in monitor_npz:
        return None
    return monitor_npz[key]


def _normalized_l2_error(lhs: np.ndarray, rhs: np.ndarray) -> float:
    numerator = np.linalg.norm(lhs - rhs)
    denominator = np.linalg.norm(rhs) + 1e-12
    return float(numerator / denominator)


def _cosine_similarity(lhs: np.ndarray, rhs: np.ndarray) -> float:
    lhs_flat = lhs.reshape(-1).astype(np.float64, copy=False)
    rhs_flat = rhs.reshape(-1).astype(np.float64, copy=False)
    numerator = float(np.dot(lhs_flat, rhs_flat))
    denominator = float(np.linalg.norm(lhs_flat) * np.linalg.norm(rhs_flat) + 1e-12)
    return numerator / denominator


def _normalize_for_display(intensity: np.ndarray) -> np.ndarray:
    arr = np.asarray(intensity, dtype=np.float64)
    p99 = float(np.percentile(arr, 99.9))
    clipped = np.clip(arr, 0.0, p99 if p99 > 0 else arr.max())
    denom = clipped.max() - clipped.min()
    if denom <= 1e-12:
        return np.zeros_like(clipped, dtype=np.float64)
    return (clipped - clipped.min()) / denom


def _draw_detectors(
    ax,
    detector_pos: np.ndarray,
    detector_shape: str,
    detector_size: float,
    color: str = "magenta",
) -> None:
    for x, y in detector_pos:
        if detector_shape == "square":
            patch = Rectangle(
                (y - detector_size / 2.0 - 0.5, x - detector_size / 2.0 - 0.5),
                detector_size,
                detector_size,
                linewidth=2,
                edgecolor=color,
                facecolor="none",
                alpha=0.6,
            )
        else:
            patch = Circle(
                (y, x),
                detector_size / 2.0,
                linewidth=2,
                edgecolor=color,
                facecolor="none",
                alpha=0.6,
            )
        ax.add_patch(patch)


def _add_zoom_panel(
    ax_out,
    ax_zoom,
    intensity_norm: np.ndarray,
    detector_pos: np.ndarray,
    detector_shape: str,
    detector_size: float,
    detector_index: int,
    title: str,
) -> None:
    det_pos = np.asarray(detector_pos[detector_index], dtype=np.float64)
    dx, dy = int(det_pos[0]), int(det_pos[1])
    crop_size = int(detector_size)
    x0, x1 = max(0, dx - crop_size), min(intensity_norm.shape[0], dx + crop_size)
    y0, y1 = max(0, dy - crop_size), min(intensity_norm.shape[1], dy + crop_size)

    if x1 <= x0 or y1 <= y0:
        ax_zoom.axis("off")
        return

    crop_img = intensity_norm[x0:x1, y0:y1]
    ax_zoom.imshow(crop_img, cmap="hot")
    ax_zoom.set_title(title)
    ax_zoom.axis("off")

    rect = Rectangle((y0, x0), y1 - y0, x1 - x0, linewidth=1, edgecolor="white", facecolor="none")
    ax_out.add_patch(rect)

    con1 = ConnectionPatch(
        xyA=(y1, x0),
        xyB=(0, 0),
        coordsA="data",
        coordsB="data",
        axesA=ax_out,
        axesB=ax_zoom,
        color="cyan",
        alpha=0.5,
        linewidth=2,
        linestyle="-",
    )
    con2 = ConnectionPatch(
        xyA=(y1, x1),
        xyB=(0, crop_img.shape[0]),
        coordsA="data",
        coordsB="data",
        axesA=ax_out,
        axesB=ax_zoom,
        color="cyan",
        alpha=0.5,
        linewidth=2,
        linestyle="-",
    )
    ax_out.add_artist(con1)
    ax_out.add_artist(con2)

    zoom_cx = dy - y0
    zoom_cy = dx - x0
    if detector_shape == "square":
        patch = Rectangle(
            (zoom_cx - detector_size / 2.0 - 0.5, zoom_cy - detector_size / 2.0 - 0.5),
            detector_size,
            detector_size,
            linewidth=2,
            edgecolor="magenta",
            facecolor="none",
            alpha=0.6,
        )
    else:
        patch = Circle(
            (zoom_cx, zoom_cy),
            detector_size / 2.0,
            linewidth=2,
            edgecolor="magenta",
            facecolor="none",
            alpha=0.6,
        )
    ax_zoom.add_patch(patch)


def _save_visualization(
    amplitude_hw: np.ndarray,
    source_path: str,
    label: int | None,
    class_name: str | None,
    detector_pos: np.ndarray,
    detector_shape: str,
    detector_size: float,
    reference_intensity: np.ndarray,
    validation_intensity: np.ndarray,
    reference_output_vec: np.ndarray,
    validation_output_vec: np.ndarray,
    reference_predicted_detector: int,
    validation_predicted_detector: int,
    save_path: str | Path,
) -> None:
    input_display = _normalize_for_display(amplitude_hw)
    reference_display = _normalize_for_display(reference_intensity)
    validation_display = _normalize_for_display(validation_intensity)

    fig, axes = plt.subplots(2, 4, figsize=(20, 10), squeeze=False)

    input_title = f"Input ({class_name if class_name else Path(source_path).name})"
    if label is not None:
        input_title += f" / label={label}"

    axes[0, 0].imshow(input_display, cmap="gray")
    axes[0, 0].set_title(input_title)
    axes[0, 0].axis("off")

    axes[0, 1].imshow(reference_display, cmap="hot")
    axes[0, 1].set_title(f"Reference Intensity / det {reference_predicted_detector}")
    _draw_detectors(axes[0, 1], detector_pos, detector_shape, detector_size)
    axes[0, 1].axis("off")

    _add_zoom_panel(
        axes[0, 1],
        axes[0, 2],
        reference_display,
        detector_pos,
        detector_shape,
        detector_size,
        reference_predicted_detector,
        f"Reference Zoom / det {reference_predicted_detector}",
    )

    axes[0, 3].bar(range(len(reference_output_vec)), reference_output_vec, color="skyblue")
    axes[0, 3].set_title("Reference Detector Values")
    axes[0, 3].set_ylim(0.0, max(1.0, float(np.max(reference_output_vec) * 1.1)))

    axes[1, 0].imshow(input_display, cmap="gray")
    axes[1, 0].set_title("Input (same sample)")
    axes[1, 0].axis("off")

    axes[1, 1].imshow(validation_display, cmap="hot")
    axes[1, 1].set_title(f"Validation Intensity / det {validation_predicted_detector}")
    _draw_detectors(axes[1, 1], detector_pos, detector_shape, detector_size)
    axes[1, 1].axis("off")

    _add_zoom_panel(
        axes[1, 1],
        axes[1, 2],
        validation_display,
        detector_pos,
        detector_shape,
        detector_size,
        validation_predicted_detector,
        f"Validation Zoom / det {validation_predicted_detector}",
    )

    axes[1, 3].bar(range(len(validation_output_vec)), validation_output_vec, color="salmon")
    axes[1, 3].set_title("Validation Detector Values")
    axes[1, 3].set_ylim(0.0, max(1.0, float(np.max(validation_output_vec) * 1.1)))

    plt.tight_layout()
    save_path = Path(save_path).expanduser().resolve()
    save_path.parent.mkdir(parents=True, exist_ok=True)
    plt.savefig(save_path, dpi=150)
    plt.close(fig)
    print(f"Saved visualization PNG: {save_path}")


def compare_case_monitor(
    case_path: str | Path,
    monitor_path: str | Path,
    save_json: str | Path | None = None,
    save_png: str | Path | None = None,
) -> dict[str, object]:
    case_path = Path(case_path).expanduser().resolve()
    monitor_path = Path(monitor_path).expanduser().resolve()

    case = np.load(case_path, allow_pickle=False)
    monitor = np.load(monitor_path, allow_pickle=False)

    amplitude_hw = case["amplitude_hw"]
    expected_hw = tuple(map(int, amplitude_hw.shape))
    reference_intensity = case["reference_intensity"]
    reference_output_vec = case["reference_output_vec"]
    reference_raw_detectors = case["reference_raw_detectors"]
    detector_pos = case["detector_pos"]
    detector_mask = case["detector_mask"]
    detector_minus = case["detector_minus"]

    case_dir = case_path.parent
    manifest_path = case_dir / "case_manifest.json"
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)
    cfg = manifest["config"]
    source_path = str(manifest.get("source_path", ""))
    label = manifest.get("label")
    class_name = manifest.get("class_name")

    lumerical_intensity = intensity_from_components(
        expected_hw,
        _load_monitor_field(monitor, "Ex"),
        _load_monitor_field(monitor, "Ey"),
        _load_monitor_field(monitor, "Ez"),
    )

    readout = detector_readout(
        lumerical_intensity,
        detector_pos=detector_pos,
        detector_size=float(cfg["detector_size"]),
        detector_shape=str(cfg["detector_shape"]),
        detector_mask=detector_mask,
        detector_minus=detector_minus,
    )

    summary = {
        "case": str(case_path),
        "monitor": str(monitor_path),
        "reference_predicted_detector": int(case["reference_predicted_detector"][0]),
        "lumerical_predicted_detector": int(readout["predicted_detector"]),
        "detector_argmax_match": bool(
            int(case["reference_predicted_detector"][0]) == int(readout["predicted_detector"])
        ),
        "reference_output_vec": reference_output_vec.tolist(),
        "lumerical_output_vec": readout["normalized"].tolist(),
        "reference_raw_detectors": reference_raw_detectors.tolist(),
        "lumerical_raw_detectors": readout["raw"].tolist(),
        "normalized_output_l2_error": _normalized_l2_error(readout["normalized"], reference_output_vec),
        "raw_detector_l2_error": _normalized_l2_error(readout["raw"], reference_raw_detectors),
        "intensity_nrmse": _normalized_l2_error(lumerical_intensity, reference_intensity),
        "intensity_cosine_similarity": _cosine_similarity(lumerical_intensity, reference_intensity),
    }

    print("Comparison summary")
    print(f"  reference detector : {summary['reference_predicted_detector']}")
    print(f"  lumerical detector : {summary['lumerical_predicted_detector']}")
    print(f"  argmax match       : {summary['detector_argmax_match']}")
    print(f"  output L2 error    : {summary['normalized_output_l2_error']:.6e}")
    print(f"  raw det L2 error   : {summary['raw_detector_l2_error']:.6e}")
    print(f"  intensity NRMSE    : {summary['intensity_nrmse']:.6e}")
    print(f"  intensity cosine   : {summary['intensity_cosine_similarity']:.6f}")

    if save_json:
        save_path = Path(save_json).expanduser().resolve()
        save_path.parent.mkdir(parents=True, exist_ok=True)
        with open(save_path, "w", encoding="utf-8") as f:
            json.dump(summary, f, indent=2, ensure_ascii=True)
            f.write("\n")
        print(f"Saved summary JSON: {save_path}")
    if save_png:
        _save_visualization(
            amplitude_hw=amplitude_hw,
            source_path=source_path,
            label=label,
            class_name=class_name,
            detector_pos=detector_pos,
            detector_shape=str(cfg["detector_shape"]),
            detector_size=float(cfg["detector_size"]),
            reference_intensity=reference_intensity,
            validation_intensity=lumerical_intensity,
            reference_output_vec=reference_output_vec,
            validation_output_vec=np.asarray(readout["normalized"], dtype=np.float64),
            reference_predicted_detector=int(case["reference_predicted_detector"][0]),
            validation_predicted_detector=int(readout["predicted_detector"]),
            save_path=save_png,
        )
    return summary


def main() -> None:
    args = parse_args()
    compare_case_monitor(
        case_path=args.case,
        monitor_path=args.monitor,
        save_json=args.save_json or None,
        save_png=args.save_png or None,
    )


if __name__ == "__main__":
    main()
