from __future__ import annotations

import argparse
import json
import os
import sys
from pathlib import Path

import numpy as np


SCRIPT_DIR = Path(__file__).resolve().parent
DEFAULT_LUMAPI_PATH = Path(r"E:\Program Files\ANSYS Inc\v252\Lumerical\api\python")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build and optionally run the Lumerical scheme-B FDTD skeleton from a prepared case."
    )
    parser.add_argument(
        "--case",
        required=True,
        help="Path to case_data.npz generated by prepare_case.py.",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Where to save detector monitor output (.npz). Default: next to case_data.npz.",
    )
    parser.add_argument(
        "--fsp",
        default="",
        help="Where to save the generated .fsp project. Default: next to case_data.npz.",
    )
    parser.add_argument(
        "--lumapi-path",
        default=str(DEFAULT_LUMAPI_PATH),
        help="Directory containing lumapi Python package.",
    )
    parser.add_argument(
        "--threads",
        type=int,
        default=4,
        help="Lumerical worker thread count.",
    )
    parser.add_argument(
        "--show",
        action="store_true",
        help="Show the Lumerical GUI instead of running offscreen.",
    )
    parser.add_argument(
        "--skip-run",
        action="store_true",
        help="Only generate the .fsp skeleton and skip fdtd.run().",
    )
    parser.add_argument(
        "--qt-debug-plugins",
        action="store_true",
        help="Enable QT_DEBUG_PLUGINS=1 before importing lumapi.",
    )
    return parser.parse_args()


def sanitize_qt_environment(enable_debug: bool = False) -> None:
    for key in ("QT_PLUGIN_PATH", "QT_QPA_PLATFORM_PLUGIN_PATH", "QT_QPA_PLATFORM"):
        os.environ.pop(key, None)
    if enable_debug:
        os.environ["QT_DEBUG_PLUGINS"] = "1"
    else:
        os.environ.pop("QT_DEBUG_PLUGINS", None)


def import_lumapi(lumapi_path: str, qt_debug_plugins: bool = False):
    sanitize_qt_environment(enable_debug=qt_debug_plugins)
    path_obj = Path(lumapi_path).expanduser().resolve()
    lumerical_root = path_obj.parents[2]
    bin_dir = lumerical_root / "bin"
    os.environ["PATH"] = f"{bin_dir};{path_obj};" + os.environ.get("PATH", "")

    if str(path_obj) not in sys.path:
        sys.path.append(str(path_obj))
    try:
        import lumapi  # type: ignore
    except ImportError as exc:
        raise ImportError(f"Could not import lumapi from {path_obj}") from exc
    return lumapi


def run_fdtd_case(
    case_path: str | Path,
    output_path: str | Path | None = None,
    fsp_path: str | Path | None = None,
    lumapi_path: str = str(DEFAULT_LUMAPI_PATH),
    threads: int = 4,
    show: bool = False,
    skip_run: bool = False,
    qt_debug_plugins: bool = False,
) -> dict[str, object]:
    case_path = Path(case_path).expanduser().resolve()
    case_dir = case_path.parent
    output_path = Path(output_path).expanduser().resolve() if output_path else (case_dir / "lumerical_monitor_output.npz")
    fsp_path = Path(fsp_path).expanduser().resolve() if fsp_path else (case_dir / "scheme_b_skeleton.fsp")

    case = np.load(case_path, allow_pickle=False)
    amplitude_hw = case["amplitude_hw"]
    x = case["x"]
    y = case["y"]
    z = case["z"]
    ex = case["Ex"]
    ey = case["Ey"]
    ez = case["Ez"]

    manifest_path = case_dir / "case_manifest.json"
    if not manifest_path.exists():
        raise FileNotFoundError(f"Manifest not found next to case file: {manifest_path}")
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    cfg = manifest["config"]
    width = int(amplitude_hw.shape[1])
    height = int(amplitude_hw.shape[0])
    pixel_size = float(cfg["pixel_size"])
    num_layers = int(cfg["num_layers"])
    distance_between_layers = float(cfg["distance_between_layers"])
    distance_to_detectors = float(cfg["distance_to_detectors"])
    detector_z = num_layers * distance_between_layers + distance_to_detectors
    z_span = detector_z + 20e-6

    lumapi = import_lumapi(lumapi_path, qt_debug_plugins=qt_debug_plugins)
    fdtd_kwargs = {"hide": not show}
    if not show and threads > 0:
        fdtd_kwargs["serverArgs"] = {"threads": str(threads)}

    with lumapi.FDTD(**fdtd_kwargs) as fdtd:
        fdtd.eval("switchtolayout; deleteall;")

        fdtd.addfdtd()
        fdtd.set("x", 0)
        fdtd.set("y", 0)
        fdtd.set("z", 0)
        fdtd.set("x span", width * pixel_size)
        fdtd.set("y span", height * pixel_size)
        fdtd.set("z span", z_span)

        fdtd.addimportedsource()
        fdtd.set("name", "src")
        fdtd.set("injection axis", "z-axis")
        fdtd.set("direction", "forward")

        fdtd.putv("x_arr", x)
        fdtd.putv("y_arr", y)
        fdtd.putv("z_arr", z)
        fdtd.putv("Ex_arr", ex)
        fdtd.putv("Ey_arr", ey)
        fdtd.putv("Ez_arr", ez)
        fdtd.eval(
            """
            EM = rectilineardataset("EM fields", x_arr, y_arr, z_arr);
            EM.addattribute("E", Ex_arr, Ey_arr, Ez_arr);
            select("src");
            importdataset(EM);
            """
        )

        fdtd.addprofile()
        fdtd.set("name", "detector_monitor")
        fdtd.set("monitor type", "2D Z-normal")
        fdtd.set("x", 0)
        fdtd.set("y", 0)
        fdtd.set("z", detector_z)
        fdtd.set("x span", width * pixel_size)
        fdtd.set("y span", height * pixel_size)

        fdtd.save(str(fsp_path))
        print(f"Saved Lumerical skeleton: {fsp_path}")

        if skip_run:
            print("Skipped fdtd.run() as requested.")
            return {
                "case_path": case_path,
                "fsp_path": fsp_path,
                "output_path": None,
                "skipped_run": True,
            }

        fdtd.run()
        result = fdtd.getresult("detector_monitor", "E")

    saved = {
        "x": np.asarray(result.get("x")),
        "y": np.asarray(result.get("y")),
        "z": np.asarray(result.get("z")),
    }
    for key in ("Ex", "Ey", "Ez", "lambda", "f"):
        if key in result:
            saved[key] = np.asarray(result[key])

    np.savez_compressed(output_path, **saved)
    print(f"Saved detector monitor output: {output_path}")
    return {
        "case_path": case_path,
        "fsp_path": fsp_path,
        "output_path": output_path,
        "skipped_run": False,
    }


def main() -> None:
    args = parse_args()
    run_fdtd_case(
        case_path=args.case,
        output_path=args.output or None,
        fsp_path=args.fsp or None,
        lumapi_path=args.lumapi_path,
        threads=args.threads,
        show=args.show,
        skip_run=args.skip_run,
        qt_debug_plugins=args.qt_debug_plugins,
    )


if __name__ == "__main__":
    main()
