from __future__ import annotations

import argparse
import json
from pathlib import Path

import numpy as np
import torch
import torch.nn.functional as F

from common import load_run_artifacts, run_python_exit_field


SCRIPT_DIR = Path(__file__).resolve().parent


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Run a far-field system-level validation for a prepared scheme-B case."
    )
    parser.add_argument(
        "--case",
        required=True,
        help="Path to case_data.npz generated by prepare_case.py.",
    )
    parser.add_argument(
        "--output",
        default="",
        help="Output npz path. Empty means <case_dir>/farfield_monitor_output.npz.",
    )
    return parser.parse_args()


def _centered_axis(length: int, pixel_size: float) -> np.ndarray:
    return (np.arange(length, dtype=np.float64) - length / 2.0) * pixel_size


def _build_sampling_grid(
    src_x: np.ndarray,
    src_y: np.ndarray,
    dst_x: np.ndarray,
    dst_y: np.ndarray,
) -> torch.Tensor:
    src_x0 = float(src_x[0])
    src_x1 = float(src_x[-1])
    src_y0 = float(src_y[0])
    src_y1 = float(src_y[-1])

    if src_x1 == src_x0 or src_y1 == src_y0:
        raise ValueError("Source coordinate range must be non-zero for resampling")

    grid_x = (dst_x - src_x0) / (src_x1 - src_x0) * 2.0 - 1.0
    grid_y = (dst_y - src_y0) / (src_y1 - src_y0) * 2.0 - 1.0
    mesh_y, mesh_x = np.meshgrid(grid_y, grid_x, indexing="ij")
    grid = np.stack([mesh_x, mesh_y], axis=-1).astype(np.float32, copy=False)
    return torch.from_numpy(grid).unsqueeze(0)


def _resample_plane_real(
    image_hw: np.ndarray,
    src_x: np.ndarray,
    src_y: np.ndarray,
    dst_x: np.ndarray,
    dst_y: np.ndarray,
) -> np.ndarray:
    image_t = torch.from_numpy(np.asarray(image_hw, dtype=np.float32)).unsqueeze(0).unsqueeze(0)
    grid_t = _build_sampling_grid(src_x, src_y, dst_x, dst_y)
    sampled = F.grid_sample(
        image_t,
        grid_t,
        mode="bilinear",
        padding_mode="zeros",
        align_corners=True,
    )
    return sampled.squeeze(0).squeeze(0).cpu().numpy()


def far_field_case(case_path: str | Path, output_path: str | Path | None = None) -> dict[str, object]:
    case_path = Path(case_path).expanduser().resolve()
    case_dir = case_path.parent
    manifest_path = case_dir / "case_manifest.json"
    with open(manifest_path, "r", encoding="utf-8") as f:
        manifest = json.load(f)

    case = np.load(case_path, allow_pickle=False)
    cfg = manifest["config"]
    run_dir = Path(manifest["run_dir"]).expanduser().resolve()
    artifacts = load_run_artifacts(run_dir)

    amplitude_hw = case["amplitude_hw"]
    expected_hw = tuple(map(int, amplitude_hw.shape))
    reference_intensity = np.asarray(case["reference_intensity"], dtype=np.float64)

    exit_result = run_python_exit_field(artifacts, amplitude_hw)
    exit_field = np.asarray(exit_result["exit_field"], dtype=np.complex128)

    wavelength = float(cfg["wavelength"])
    pixel_size = float(cfg["pixel_size"])
    distance = float(cfg["distance_to_detectors"])

    height, width = expected_hw
    x_far = np.fft.fftshift(np.fft.fftfreq(width, d=pixel_size)) * wavelength * distance
    y_far = np.fft.fftshift(np.fft.fftfreq(height, d=pixel_size)) * wavelength * distance

    far_field = np.fft.fftshift(np.fft.fft2(np.fft.ifftshift(exit_field))) * (pixel_size**2)
    far_intensity = (np.abs(far_field) ** 2) / ((wavelength * distance) ** 2 + 1e-30)

    target_x = _centered_axis(width, pixel_size)
    target_y = _centered_axis(height, pixel_size)
    resampled_intensity = _resample_plane_real(far_intensity, x_far, y_far, target_x, target_y)
    resampled_intensity = np.maximum(resampled_intensity.astype(np.float64, copy=False), 0.0)

    ref_total_energy = float(reference_intensity.sum())
    far_total_energy = float(resampled_intensity.sum())
    if far_total_energy > 0 and ref_total_energy > 0:
        resampled_intensity *= ref_total_energy / far_total_energy

    ex_monitor = np.sqrt(resampled_intensity).T[:, :, None].astype(np.complex64)
    ey_monitor = np.zeros_like(ex_monitor)
    ez_monitor = np.zeros_like(ex_monitor)

    output_path = (
        Path(output_path).expanduser().resolve()
        if output_path
        else (case_dir / "farfield_monitor_output.npz").resolve()
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    np.savez_compressed(
        output_path,
        Ex=ex_monitor,
        Ey=ey_monitor,
        Ez=ez_monitor,
        farfield_intensity_hw=resampled_intensity.astype(np.float32, copy=False),
        farfield_exit_intensity_hw=np.asarray(exit_result["exit_intensity"], dtype=np.float32),
        x_far=x_far.astype(np.float64, copy=False),
        y_far=y_far.astype(np.float64, copy=False),
        x_target=target_x.astype(np.float64, copy=False),
        y_target=target_y.astype(np.float64, copy=False),
    )
    print(f"Saved far-field monitor output: {output_path}")
    return {
        "case_path": str(case_path),
        "output_path": str(output_path),
    }


def main() -> None:
    args = parse_args()
    far_field_case(
        case_path=args.case,
        output_path=args.output or None,
    )


if __name__ == "__main__":
    main()
